//
//  Problem002.m
//  ProjectEuler-iOS
//
//  Created by Joseph Wilkerson on 3/20/15.
//  Copyright (c) 2015 Joseph Wilkerson. All rights reserved.
//

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */


#import "Problem002.h"

@implementation Problem002

- (void)solve
{
    [super solve];
    
    int sum = 0;
    int currentTerm = 1;
    int lastTerm = 1;
    int tempTerm = 1;
    while (currentTerm < 4000000)
    {
        tempTerm = currentTerm;
        currentTerm += lastTerm;
        lastTerm = tempTerm;
        if (currentTerm % 2 == 0) sum += currentTerm;
    }
    
    self.answerString = [NSString stringWithFormat:@"%d",sum];
}

@end
